name: "Bug 报告"
description: 报告你遇到的问题并附上最近的日志
title: "[BUG] "
labels: ["bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
        感谢提交 Bug！请尽量完整地提供信息，便于快速定位问题。

  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么？
      description: 清晰描述问题现象与你原本期望的行为。
      placeholder: 比如：点击下载后卡住；或生成的 EPUB 无法打开…
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 分步说明如何复现该问题。
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true

  - type: input
    id: book
    attributes:
      label: 相关书籍ID/分享链接（如有）
      placeholder: 例如：123456 或 https://…
    validations:
      required: false

  - type: input
    id: env
    attributes:
      label: 环境信息
      description: 操作系统/运行方式（TUI/旧CLI）/Python版本（如适用）/软件版本
      placeholder: Windows 11, 新版 TUI, vX.Y.Z
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 最新一次日志（必须）
      description: 请拖拽上传 logs/latest.log 或最近的日志ZIP；如不方便上传，请粘贴关键信息。
      render: text
      placeholder: 将日志文件拖拽到此处，或粘贴内容。
    validations:
      required: true
