name: "Feature 请求"
description: 提出新功能或改进建议
title: "[Feature] "
labels: ["enhancement", "new"]
body:
  - type: markdown
    attributes:
      value: |
        说说你的需求、使用场景与预期收益。

  - type: textarea
    id: feature-desc
    attributes:
      label: 功能描述
      description: 简要说明你希望实现的功能。
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 使用场景/动机
      description: 为什么需要这个功能？它将解决什么问题？
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 其他补充
      description: 相关截图、参考链接、可能的实现思路等。
    validations:
      required: false
