name: PR 标签触发多平台构建

on:
  pull_request_target:
    types: [labeled]

jobs:
  cancel_if_unrelated:
    runs-on: ubuntu-latest
    # 只保留 run-build，其它标签添加则取消
    if: github.event.label.name != 'run-build'
    steps:
      - name: 非目标标签，取消本次 Workflow
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    if: github.event.label.name == 'run-build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR 源分支代码
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Checkout private repo B
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Fanqie-Novel-Official-API-Helper
          token: ${{ secrets.PYD_PAT }}
          path: B

      - name: Install B's build dependencies (Linux)
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          if [ -f B/requirements.txt ]; then
            pip install -r B/requirements.txt
          fi

      - name: Build Cython extension from B (Linux)
        run: |
          cd B
            python setup.py build_ext --inplace
          cd ..

      - name: Copy compiled B extension into A's root (Linux)
        run: |
          cp B/client_mod.*.so . || true

      - name: Cache Dependencies (Linux)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies (Linux)
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pyinstaller

      - name: Build Executable (Linux)
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
              VERSION="${{ github.ref_name }}"
          else
              VERSION="sha-${{ github.sha }}"
          fi
          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            --hidden-import=portalocker \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-Linux_amd64-$VERSION \
            --clean \
            main.py

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/TomatoNovelDownloader-*

  build-linux-arm64:
    if: github.event.label.name == 'run-build'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout PR 源分支代码
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Checkout private repo B
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Fanqie-Novel-Official-API-Helper
          token: ${{ secrets.PYD_PAT }}
          path: B

      - name: Install B's build dependencies (Linux ARM64)
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          if [ -f B/requirements.txt ]; then
            pip install -r B/requirements.txt
          fi

      - name: Build Cython extension from B (Linux ARM64)
        run: |
          cd B
            python setup.py build_ext --inplace
          cd ..

      - name: Copy compiled B extension into A's root (Linux ARM64)
        run: |
          cp B/client_mod.*.so . || true

      - name: Cache Dependencies (Linux ARM64)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies (Linux ARM64)
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pyinstaller

      - name: Build Executable (Linux ARM64)
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
              VERSION="${{ github.ref_name }}"
          else
              VERSION="sha-${{ github.sha }}"
          fi
          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            --hidden-import=portalocker \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-Linux_arm64-$VERSION \
            --clean \
            main.py

      - name: Upload Linux ARM64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-build
          path: dist/TomatoNovelDownloader-*

  build-windows:
    if: github.event.label.name == 'run-build'
    runs-on: windows-latest
    steps:
      - name: Checkout PR 源分支代码
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Checkout private repo B
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Fanqie-Novel-Official-API-Helper
          token: ${{ secrets.PYD_PAT }}
          path: B

      - name: Install B's build dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          if (Test-Path "B\\requirements.txt") {
            pip install -r B\\requirements.txt
          }
        shell: powershell

      - name: Build Cython extension from B (Windows)
        run: |
          cd B
          python setup.py build_ext --inplace
          cd ..
        shell: powershell

      - name: Copy compiled B extension into A's root (Windows)
        run: |
          Copy-Item "B\\client_mod*.pyd" "." -Force
        shell: powershell

      - name: Cache Dependencies (Windows)
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: powershell

      - name: Download UPX (Windows)
        run: |
          $url = "https://github.com/upx/upx/releases/download/v5.0.0/upx-5.0.0-win64.zip"
          Invoke-WebRequest -Uri $url -OutFile upx.zip
          Expand-Archive -Path upx.zip -DestinationPath upx
        shell: powershell

      - name: Build Executable (Windows)
        run: |
          $upxDir = "$pwd\upx\upx-5.0.0-win64"
          if (Test-Path "$upxDir\upx.exe") {
              icacls "$upxDir\upx.exe" /grant Everyone:F
          }
          if ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}"
          } else {
            $version = "sha-${{ github.sha }}"
          }
          pyinstaller --onefile `
            --upx-dir "$upxDir" `
            --collect-data fake_useragent `
            --hidden-import=portalocker `
            -i img/Tomato-downlaoder-ico.ico `
            --name=TomatoNovelDownloader-Win64-$version `
            --clean `
            main.py
        shell: powershell

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist\TomatoNovelDownloader-*.exe

  build-macos:
    if: github.event.label.name == 'run-build'
    runs-on: macos-latest
    steps:
      - name: Checkout PR 源分支代码
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Checkout private repo B
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Fanqie-Novel-Official-API-Helper
          token: ${{ secrets.PYD_PAT }}
          path: B

      - name: Install B's build dependencies (macOS arm64)
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          if [ -f B/requirements.txt ]; then
            pip install -r B/requirements.txt
          fi

      - name: Build Cython extension from B (macOS arm64)
        run: |
          cd B
            python setup.py build_ext --inplace
          cd ..

      - name: Copy compiled B extension into A's root (macOS arm64)
        run: |
          cp B/client_mod.*.so . || true

      - name: Cache Dependencies (macOS arm64)
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies (macOS arm64)
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pyinstaller

      - name: Build Executable (macOS arm64)
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
              VERSION="${{ github.ref_name }}"
          else
              VERSION="sha-${{ github.sha }}"
          fi
          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            --hidden-import=portalocker \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-macOS_arm64-$VERSION \
            --clean \
            main.py

      - name: Upload macOS arm64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: dist/TomatoNovelDownloader-macOS_arm64-*

  build-macos-intel:
    if: github.event.label.name == 'run-build'
    runs-on: macos-13   # Intel x86_64 runner
    steps:
      - name: Checkout PR 源分支代码
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'

      - name: Checkout private repo B
        uses: actions/checkout@v4
        with:
          repository: zhongbai2333/Fanqie-Novel-Official-API-Helper
          token: ${{ secrets.PYD_PAT }}
          path: B

      - name: Install B's build dependencies (macOS Intel)
        run: |
          python -m pip install --upgrade pip
          pip install Cython
          if [ -f B/requirements.txt ]; then
            pip install -r B/requirements.txt
          fi

      - name: Build Cython extension from B (macOS Intel)
        run: |
          cd B
            python setup.py build_ext --inplace
          cd ..

      - name: Copy compiled B extension into A's root (macOS Intel)
        run: |
          cp B/client_mod.*.so . || true

      - name: Cache Dependencies (macOS Intel)
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies (macOS Intel)
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pyinstaller

      - name: Build Executable (macOS Intel)
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
              VERSION="${{ github.ref_name }}"
          else
              VERSION="sha-${{ github.sha }}"
          fi
          pyinstaller \
            --onefile \
            --strip \
            --exclude-module _bootlocale \
            --exclude-module _cffi_backend \
            --collect-data fake_useragent \
            --hidden-import=portalocker \
            -i img/Tomato-downlaoder-ico.ico \
            --name=TomatoNovelDownloader-macOS_amd64-$VERSION \
            --clean \
            main.py

      - name: Upload macOS Intel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel-build
          path: dist/TomatoNovelDownloader-macOS_amd64-*

  build-on-label:
    needs: [build-linux, build-linux-arm64, build-windows, build-macos, build-macos-intel]
    if: github.event.label.name == 'run-build'
    runs-on: ubuntu-latest
    steps:
      - name: 评论 & 删除标签
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ 多平台构建完成（含 macOS Intel），已生成可执行文件。'
            });
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: context.payload.label.name
            });